spring: 
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.150.59.156:3306/daobunso?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: manager
    password: $2a$08$bZJeeZKCnq5fU.aiPPsgtuIn.Xs99Eu0.oaBiWjohOzZPNEoPa7R6
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: daobunso.company@gmail.com
    password: dnvogsyuevpyrnig
    properties:
      mail:
        smtp:
          auth: true
          starttls :
            enable: true  
  messages:
    encoding: UTF-8
    basename: i18n/area8, i18n/feedback, i18n/header, i18n/serviceIntro, i18n/verifyemail, i18n/profiles, i18n/shoppingcart, i18n/serviceproject3, i18n/serviceproject2, i18n/serviceproject1, i18n/order, i18n/login, i18n/frontpage, i18n/aboutus, i18n/shopping, i18n/userterms, i18n/problem, i18n/service
    cache-duration: 3600
server:
  port: 443
  ssl:
    key-store: "classpath:server.jks"
    key-store-password: "daobunso"
    key-store-type: PKCS12
thymeleaf:
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5=
redis:
    host: 127.0.0.1
    port: 6379
    
