spring: 
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.150.59.156:3306/daobunso?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: manager
    password: $2a$08$bZJeeZKCnq5fU.aiPPsgtuIn.Xs99Eu0.oaBiWjohOzZPNEoPa7R6
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: grfmbiu324568@gmail.com
    password: wyhjhfzkwdyplata
    properties:
      mail:
        smtp:
          auth: true
          starttls :
            enable: true  
  messages:
    encoding: UTF-8
    basename: i18n/order, i18n/login, i18n/frontpage
    cache-duration: 3600
server:
  port: 443
  ssl:
    key-store: "classpath:server.pfx"
    key-store-password: "daobunso"
    key-store-type: PKCS12
thymeleaf:
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5=
redis:
    host: 127.0.0.1
    port: 6379
    
Conf: #綠界XML
  OperatingMode: Test
  MercProfile: Stage_Account
  IsProjectContractor: N
  
  MerchantInfo:
        MInfo name: "Stage_Account"
        MerchantID: 2000132
        HashKey: 5294y06JbISpM5x9
        HashIV: v77hoKGq4kWxNNIS
  IgnorePayment: 
  
  
  
  
  logging:
  config:  classpath:log4j2.xml
  level:
    root: INFO
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
